name: Backport Trigger

on:
  pull_request_review_comment:
    types: [created]

jobs:
  launchBackportBuild:
    name: Starting Backport Build
    runs-on: windows-latest
    steps:
      - name: Echo the comment
        run: Write-Host "$(github.event.comment.body)"
        shell: pwsh
