name: Backport Trigger

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      foobar:
        description: 'x'
        required: true
        default: 'foo'

jobs:
  launchBackportBuild:
    runs-on: windows-latest
    steps:
      # NOTE: This is one step because of a known vulnerability in workflow commands: https://bugs.chromium.org/p/project-zero/issues/detail?id=2070&can=2&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&cells=ids
      - name: Launch ADO Backport Build
        run: |
          Write-Host "${{ github.event_name }}"
          ($repoOwner, $repoName) = "${{ github.repository }}".Split("/")

          $launchURI = "https://dev.azure.com/${{ secrets.ADO_PROJECTCOLLECTION }}/${{ secrets.ADO_PROJECT }}/_apis/build/builds?api-version=6.0"
          $parameters = @{
            BackportRepoName = "$repoName";
            BackportRepoOrg = "$repoOwner";
            BackportTargetBranch = "${{ env.GITHUB_REF }}";
            BackportPRNumber = ""
          } | ConvertTo-Json

          $json = @{
            definition = @{ id = "${{ secrets.ADO_PIPELINEID }}" };
            sourceBranch = "yaml-pipeline"; // This is hardcoded for now
            parameters = $parameters
          } | ConvertTo-Json

          Write-Host "Posting to $launchURI`:"
          Write-Host "$json"
          $encoded = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes(":${{ secrets.ADO_BUILDPAT }}"))
          $headers = @{ Authorization = "Basic $encoded"}
        shell: pwsh
