name: Backport Trigger

on:
  issue_comment:
    types: [created]

jobs:
  launchBackportBuild:
    if: github.event.issue.pull_request != '' && startswith(github.event.comment.body, '@vs-mobiletools-engineering-service2 backport')
    
    uses: xamarin/backport-bot-action/.github/workflows/backport-action.yml@v1.1
    with:
      pull_request_url: ${{ github.event.issue.pull_request.url }}
      comment_author: ${{ github.actor }}
      github_repository: ${{ github.repository }}
      use_fork: false
    secrets:
      ado_organization: ${{ secrets.ADO_PROJECTCOLLECTION }}
      ado_project: ${{ secrets.ADO_PROJECT }}
      backport_pipeline_id: ${{ secrets.BACKPORT_PIPELINEID }}
      ado_build_pat: ${{ secrets.ADO_BUILDPAT }}
      github_account_pat: ${{ secrets.SERVICEACCOUNT_PAT }}

